dockerfile: omit inadvertant component upgrades
appsody/appsody-buildah pull request #7
Opened 2019-09-06 14:06 UTC by gireeshpunathil

An issue was reported as part of CRI-O pipeline testsing,
where a class of systems (specifically RHEL 7) were  failing.

While we stuck to `quay.io/buildah/stable:v1.9.0` , 
the `yum update` construct in the Dockerfile was 
upgrading the installed components in the image,
including `buildah`, taking us back to square one.

excerpts from `yum upgrade`:
```
Upgraded:
  audit-libs-3.0-0.9.20190507gitf58ec40.fc30.x86_64                             
  buildah-1.10.1-2.git8c1c2c5.fc30.x86_64                                       
...
```

All what we want is just `wget`, so skip `yum update`.

2019-09-06 15:28 UTC, gireeshpunathil commented
the testing revealed further issues w.r.t files being copied; so please wait, I may have updates to this. thanks!

2019-09-07 10:22 UTC, gireeshpunathil commented
this is now up for review too! , but land-able after https://github.com/appsody/appsody/pull/283

2019-09-07 10:22 UTC, gireeshpunathil commented
cc @chilanti @ianpartridge @neeraj-ladd @kilnerm

2019-09-07 11:45 UTC, neeraj-laad requested changes

2019-09-07 11:45 UTC, neeraj-laad commented on Dockerfile
> +RUN yum -y install wget
Not sure I understand the reason for this change? We do not want to pull in other yum updates?

2019-09-07 12:56 UTC, neeraj-laad commented on Dockerfile
> +RUN yum -y install wget
just read the PR comments and noe I understand why we are skipping that.

2019-09-07 12:56 UTC, neeraj-laad approved these changes
LGTM

2019-09-07 12:56 UTC, merged